config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  # get '/' => "homes#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :microposts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @posts = Micropost.all
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def new
    @post = Micropost.new
  end

  def create
    @post = Micropost.new(post_params)
    @post.save
    redirect_to root_path
  end

  def show
    @post = Micropost.find(params[:id])
  end

  def edit
    @post = Micropost.find(params[:id])
  end

  def update
    @post = Micropost.find(params[:id])
    @post.update(post_params)
    redirect_to micropost_path(@post.id)
  end
  private

  def post_params
    params.require(:micropost).permit(:content, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/homes/top.html.erb
<h1>topページ</h1>
<%= link_to "投稿画面", new_micropost_path %>
<% @posts.each do | post | %>
  <p><%= "#{post[:content]}" %></p>
  <%= attachment_image_tag post, :image, :fill, 300, 300, format:'jpeg' %>
  <%= link_to "詳細画面", micropost_path(post.id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/edit.html.erb
<%= form_with model: @post, local: true do |f|%>
<%= f.text_field :content %>
<%= f.attachment_field :image %>
<%= f.submit "更新" %>
<% end %>

app/views/microposts/new.html.erb
<%= form_with  model: @post, local:true do |f| %>
<%= f.text_field :content %>
<%= f.attachment_field :image %>
<%= f.submit "投稿" %>
<% end %>

app/views/microposts/show.html.erb
<%= "id:#{@post.id}"%>
<%= "content:#{@post.content}" %>
<%= attachment_image_tag @post, :image, :fill, 300, 300, format:'jpeg' %>
<%= "作成日時:#{@post.created_at}" %>
<%= "編集日時:#{@post.updated_at}" %>
<%= link_to "編集", edit_micropost_path(@post.id) %>